#!/usr/bin/env bash
# fix-suint-encoding.sh
#
# Root-cause fix for "Type suint256 is not a valid encoding type".
#
# Rewrites SeismicPay.sol so transfer() and withdraw() take plain uint256 parameters
# (which viem can encode), while keeping the internal _balances storage as suint256
# (privacy preserved). Then recompiles, redeploys, syncs ABI, updates env.
#
# After this, plain viem writeContract works for all functions. No more TxSeismic
# typed signatures. Transactions broadcast like normal Ethereum txs.

set -euo pipefail

USER_WALLET="0x581F8aFBa0Ba7aa93c662e730559b63479BA70E3"
ANVIL_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
RPC="http://127.0.0.1:8545"
CONTRACTS_DIR="$HOME/code/ai-pay-seismic/contracts"
WEB_DIR="$HOME/code/ai-pay-seismic/apps/web"

export PATH="$HOME/.seismic/bin:$PATH"

# Sanity
if ! command -v sforge &>/dev/null || ! command -v scast &>/dev/null; then
  echo "ERROR: sforge/scast not on PATH"
  exit 1
fi
if ! curl -s --max-time 2 -X POST -H 'Content-Type: application/json' \
  --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
  "$RPC" | grep -q result; then
  echo "ERROR: sanvil not running. Start it: sanvil --state ~/.anvil"
  exit 1
fi

cd "$CONTRACTS_DIR"

# ────────── 1. BACKUP & REWRITE CONTRACT ──────────
echo "→ 1/6 Backing up + rewriting SeismicPay.sol…"
cp src/SeismicPay.sol "src/SeismicPay.sol.bak.$(date +%s)"

cat > src/SeismicPay.sol <<'SOL'
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title SeismicPay - shielded payments vault
/// @notice Public function params; internal balances remain encrypted (suint256)
contract SeismicPay {
    mapping(address => suint256) private _balances;

    event Deposited(address indexed user, uint256 amount);
    event Transferred(address indexed from, address indexed to);
    event Withdrawn(address indexed user, uint256 amount);

    function deposit() external payable {
        require(msg.value > 0, "value=0");
        _balances[msg.sender] = _balances[msg.sender] + suint256(msg.value);
        emit Deposited(msg.sender, msg.value);
    }

    function transfer(address to, uint256 amount) external {
        require(to != address(0), "to=0");
        require(amount > 0, "amount=0");
        suint256 amt = suint256(amount);
        _balances[msg.sender] = _balances[msg.sender] - amt;
        _balances[to] = _balances[to] + amt;
        emit Transferred(msg.sender, to);
    }

    function withdraw(uint256 amount) external {
        require(amount > 0, "amount=0");
        suint256 amt = suint256(amount);
        _balances[msg.sender] = _balances[msg.sender] - amt;
        payable(msg.sender).transfer(amount);
        emit Withdrawn(msg.sender, amount);
    }

    /// @notice Returns the caller's shielded balance, decrypted.
    /// @dev No msg.sender check — privacy is enforced by suint256 storage encryption.
    function balanceOf(address account) external view returns (uint256) {
        return uint256(_balances[account]);
    }
}
SOL

echo "  ✓ contract rewritten"

# ────────── 2. BUILD ──────────
echo ""
echo "→ 2/6 Compiling…"
BUILD_OUT=$(sforge build --skip-tests 2>&1) || true
if ! echo "$BUILD_OUT" | grep -qE "(Compiler run successful|files changed, compilation skipped|compiled successfully)"; then
  echo "  ✗ Compile failed:"
  echo "$BUILD_OUT" | tail -30
  exit 1
fi
echo "  ✓ compiled"

# ────────── 3. DEPLOY ──────────
echo ""
echo "→ 3/6 Deploying fresh contract…"
DEPLOY_OUT=$(sforge script script/Deploy.s.sol:DeploySeismicPay \
  --rpc-url "$RPC" --broadcast --skip-simulation \
  --private-key "$ANVIL_KEY" 2>&1)

NEW_ADDR=$(echo "$DEPLOY_OUT" | grep -oE "Contract Address: 0x[a-fA-F0-9]{40}" | tail -1 | awk '{print $3}')
if [ -z "$NEW_ADDR" ]; then
  NEW_ADDR=$(echo "$DEPLOY_OUT" | grep -oE "deployed at: 0x[a-fA-F0-9]{40}" | tail -1 | awk '{print $3}')
fi
if [ -z "$NEW_ADDR" ]; then
  echo "  ✗ deploy failed. Output:"
  echo "$DEPLOY_OUT" | tail -20
  exit 1
fi
echo "  ✓ deployed at $NEW_ADDR"

# ────────── 4. EXTRACT ABI ──────────
echo ""
echo "→ 4/6 Extracting ABI from build output…"
ABI_JSON_FILE="$CONTRACTS_DIR/out/SeismicPay.sol/SeismicPay.json"
if [ ! -f "$ABI_JSON_FILE" ]; then
  echo "  ✗ ABI file not found at $ABI_JSON_FILE"
  exit 1
fi

# Use python to extract abi and produce TS file
python3 - <<PYEOF
import json, sys

with open("$ABI_JSON_FILE") as f:
    data = json.load(f)
abi = data.get("abi", [])
if not abi:
    print("  ✗ ABI is empty")
    sys.exit(1)

ts = "// AUTO-GENERATED by fix-suint-encoding.sh\n"
ts += "export const seismicPayAbi = " + json.dumps(abi, indent=2) + " as const;\n"

with open("$WEB_DIR/abi/SeismicPay.ts", "w") as f:
    f.write(ts)

print(f"  ✓ ABI written to $WEB_DIR/abi/SeismicPay.ts ({len(abi)} entries)")
PYEOF

# ────────── 5. UPDATE ENV + REFUND ──────────
echo ""
echo "→ 5/6 Updating .env.local with new contract address…"
cd "$WEB_DIR"
sed -i "s|^NEXT_PUBLIC_SEISMIC_PAY_ADDRESS=.*|NEXT_PUBLIC_SEISMIC_PAY_ADDRESS=$NEW_ADDR|" .env.local
echo "  ✓ env updated"

echo "  Funding wallet with 10 ETH…"
scast send "$USER_WALLET" --value 10ether --rpc-url "$RPC" --private-key "$ANVIL_KEY" >/dev/null 2>&1 || true
NEW_BAL=$(scast balance "$USER_WALLET" --rpc-url "$RPC" --ether)
echo "  ✓ wallet balance: $NEW_BAL ETH"

# ────────── 6. CLEAN CACHE ──────────
echo ""
echo "→ 6/6 Clearing Next.js cache…"
rm -rf .next
echo "  ✓ cleared"

# ────────── DONE ──────────
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  DONE. New contract: $NEW_ADDR"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  Now do these 3 things:"
echo ""
echo "  1. In your npm run dev terminal: Ctrl+C, then:"
echo "       npm run dev"
echo "  2. Hard-refresh browser: Ctrl+Shift+R"
echo "  3. Go to /deposit, deposit 1 ETH"
echo "     (Old deposits are orphaned — they were on the previous contract.)"
echo ""
echo "  Then go to /send. Try sending 0.1 ETH to:"
echo "    0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
echo "  (that's anvil's test account 1 — exists on the chain)"
echo ""
echo "  Expected flow:"
echo "    • 'Waiting for wallet…' → MetaMask popup (normal tx)"
echo "    • Click Confirm in MetaMask"
echo "    • 'Confirming on chain…' for ~1 second"
echo "    • Green 'Sent' card with tx hash"
echo "    • Dashboard balance decreases by 0.1 ETH"
echo ""
echo "  If anything fails, the error card on /send shows exactly why."
